### PR TITLE
Convert existing asides to margin notes; showcase template

### PR DESCRIPTION
**Pull request by KennethWangDotDev**
Existing right-hand content has all been converted to margin notes.

Events page now looks like Portfolio page using the new `showcase` template. The textual content for each item is the entire individual Event content by default, but you can add an `excerpt` to the front-matter of each Event. If there is an `excerpt`, then the `excerpt` will be shown instead. I added a test event to demonstrate the Excerpt feature.

### CODE REVIEW

**Comment by fj** [comment]
This looks excellent, but I'm noticing a few minor visual bugs on the homepage.

screenshot_2016-04-25_16-17-41

The icons should be vertically centered with the dates, and they should stay under the horizontal header line -- otherwise they start crowding out the items in the adjacent section.

**Comment by fj** [comment]
Also, a note to myself -- I need to think of some way where I can include multiple document fragments in a single document so I can get the summary information separate from the full event information. The `excerpt` works but it has to be YAML-compatible and I think I may want something a bit richer than that.

**Comment by KennethWangDotDev** [comment]
I did not get the icon misalignment bug in my tests. Could be a browser-specific bug with the way font-awesome is displayed. I'll take another look at it tonight with multiple browsers.

**Comment by fj** [comment]
Gotcha. I'm using Chrome 50.0.2661.86 on Linux, fwiw.

**Comment by KennethWangDotDev** [comment]
Let me know if the latest update screwed anything up (any conflicts or code from old version). I think I should have created a new branch instead and created a new PR.

**Comment by fj** [comment]
This looks good visually, but is it a little hacky that it's so specific with respect to placement? We don't seem to use `em`s anywhere else for this.

```
.list-item-title--compact {
  margin: 0;
  padding: .5rem 0;
  position: relative;
  .jf-i {
    font-size: 0.9em;    // em vs. rem?
    position: absolute;  
    top: 0.5em;          // em vs. rem?
    left: -1.45em;       // em vs. rem?
  }
}

/* Fix for home page icon misalignment */
.home-list .jf-i {
  top: 1.15em;           // em vs. rem?
}
```

**Comment by KennethWangDotDev** [comment]
Another method that does not involve `position: absolute` and tinkering with `top` and `left` is using `margin-left` with a negative value. However, the current method of `position: absolute` is more precise and more foolproof.

The `font-size: 0.9em` should definitely be in `em` since it then becomes relative to the `font-size`. For example, the Blog entries' title `font-size` is way bigger than the home page list items, and we want the icon to be similar in size to the `font-size` of the titles.

For the positioning, there is only minute pixel differences between `em` and `rem`, and either could be used to the same effect.

**Pull request merged**
